SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 700

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_BASE_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_BASE_SHOOT_SPEED = 500
PLAYER_BASE_SHOOT_COOLDOWN = 0.3

BULLET_BASE_RADIUS = 5

TIME_MULTIPLIER_MAGIC = 0.001
